#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_DAD,
    SP_NAME_VIKI,
    SP_NAME_TORI,
    SP_NAME_NICO,
    SP_NAME_PARSLEY,
    SP_NAME_SAGE,
    SP_NAME_BASIL,
    SP_NAME_ROSEMARY,
    SP_NAME_CORI,
    SP_NAME_DILLION,
    SP_NAME_REGENO,
    SP_NAME_THYME,
    SP_NAME_PROF,
    SP_NAME_IDK,
    SP_NAME_COUNT,
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
