gText_Birch_Welcome::
	.string "Hi! Sorry to keep you all waiting!\p"
	.string "Welcome one and all!\p"
	.string "My name is Professor Tulipifera.\p"
	.string "But most just call me Professor\n"
	.string "Tulip.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "Sister: {PLAYER}!!!.\p"
	.string "Come on already we're gonna be late\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Hello?\p"
	.string "Which do you want to play as?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "a girl?\n"
	.string "Or a boy?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What name do you wanna go by?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Hi! Sorry to keep you all waiting!\p"
	.string "Welcome one and all!\p"
	.string "My name is Professor Tulipifera.\p"
	.string "But most just call me Professor\n"
	.string "Tulip.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
